[build]
  publish = "public" # Folder for your static site (HTML, CSS, JS)
  functions = "functions" # Folder for your Firebase functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
